# Generated by Django 4.2.1 on 2023-05-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_disco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='data',
            field=models.IntegerField(),
        ),
    ]
